title: [State(Art)](https://state-of-the-art.org)
description: "Jonathan's thoughts on the state of the art in software design."
google_analytics:
show_downloads: true
theme: jekyll-theme-midnight

gems:
  - jekyll-mentions
