title: State(Art)
description: "Jonathan's thoughts on the state of the art in software design."
author: Jonathan Locke
google_analytics:
show_downloads: true
theme: jekyll-theme-midnight
gems:
  - jekyll-mentions
plugins:
  - jekyll-feed
