name: State(Art)
title: State(Art)
description: "Jonathan's thoughts on the state of the art in software design."
author: Jonathan Locke
url: https://state-of-the-art.org/
google_analytics:
show_downloads: true
theme: jekyll-theme-midnight
gems:
  - jekyll-mentions
  - jekyll-feed
plugins:
  - jekyll-feed
