@startuml

    !include lexakai.theme

    title "Data - Validation"

    interface FailureReporter
    interface MessageCounter
    interface Validator

    Validator <|-- BaseValidator
    abstract class BaseValidator
    {
        --(validation)--
        #void onValidate()
        #void validate(Validator)
        --(checks)--
        +boolean isValid()
        #boolean isEmpty(String value)
        #boolean isEmpty(Collection<?>)
        --(messaging)--
        #Glitch glitch(String message, Object... parameters)
        #Glitch glitchIf(boolean invalid, String message, Object... parameters)
        #OperationHalted halt(String message, Object... parameters)
        #Problem problem(String message, Object... parameters)
        #Problem problemIf(boolean invalid, String message, Object... parameters)
        #Quibble quibble(String message, Object... parameters)
        #Quibble quibbleIf(boolean invalid, String message, Object... parameters)
        #Warning warning(String message, Object... parameters)
        #Warning warningIf(boolean invalid, String message, Object... parameters)
    }

    interface Listener
    Listener <|-- FailureReporter
    interface FailureReporter
    {
        +void report(Message)
    }

    interface Listener
    Listener <|-r- MessageCounter
    interface MessageCounter
    {
        +Count count(Message.Status type)
        +Count count(Class<? extends Message> type)
        +Count countWorseThanOrEqualTo(Message.Status)
    }

    ObjectList <|-- MessageList
    MessageCounter <|-r- MessageList
    class MessageList
    {
        +MessageList(Matcher<Message>)
        +MessageList(Maximum, Matcher<Message>)
        +StringList formatted()
        +ObjectList<Message> messages(Class<? extends Message> type)
        +StringList statistics(Message.Status... statuses)
        +StringList statisticsByType(Class<? extends Message>... types)
    }

    Validatable -l-> ValidationType : "how to validate"
    Validatable -l-> Validator : "provides"
    interface Validatable
    {
        +Validator validator()
        +Validator validator(ValidationType)
        +boolean isValid()
        +boolean isValid(Listener)
    }

    MessageList <|-- ValidationIssues
    class ValidationIssues
    {
        +ValidationIssues()
        +boolean isValid()
    }

    class ValidationType
    {
        +ValidationType(String)
        +boolean shouldValidate(Class<?> type)
        +ValidationType exclude(Class<?> type)
        +ValidationType include(Class<?> type)
    }

    Validator --> Listener : "reports to"
    interface Validator
    {
        +boolean validate(Listener)
        +boolean validate()
    }

@enduml

